-- Migration: Create daily_summaries table for pre-aggregated daily statistics
-- Supports: 005-daily-reset feature
--
-- This table stores aggregated daily statistics for fast analytics loading.
-- Data is generated by a nightly cron job that runs at the top of each hour,
-- processing users whose local midnight has passed.

-- ============================================================================
-- Prerequisites: Add timezone column to user_profiles
-- ============================================================================

-- Add timezone column to user_profiles if it doesn't exist
-- This is needed for the cron job to detect midnight in each user's local time
ALTER TABLE public.user_profiles
  ADD COLUMN IF NOT EXISTS timezone TEXT NOT NULL DEFAULT 'UTC';

-- Add index for efficient cron job queries (find users in midnight hour)
CREATE INDEX IF NOT EXISTS idx_user_profiles_timezone
  ON public.user_profiles(timezone);

COMMENT ON COLUMN public.user_profiles.timezone IS
  'IANA timezone string (e.g., America/New_York). Used for determining user''s local midnight.';

-- ============================================================================
-- Table: daily_summaries
-- ============================================================================

CREATE TABLE public.daily_summaries (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.user_profiles(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  total_stints INTEGER NOT NULL DEFAULT 0,
  total_focus_seconds INTEGER NOT NULL DEFAULT 0,
  total_pause_seconds INTEGER NOT NULL DEFAULT 0,
  project_breakdown JSONB NOT NULL DEFAULT '[]'::jsonb,
  completed_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- Ensure one summary per user per date
  CONSTRAINT unique_user_date UNIQUE (user_id, date),

  -- Non-negative constraints
  CONSTRAINT total_stints_non_negative CHECK (total_stints >= 0),
  CONSTRAINT total_focus_seconds_non_negative CHECK (total_focus_seconds >= 0),
  CONSTRAINT total_pause_seconds_non_negative CHECK (total_pause_seconds >= 0)
);

-- ============================================================================
-- Indexes
-- ============================================================================

-- Primary access pattern: Get summaries for a user within date range
CREATE INDEX idx_daily_summaries_user_date
  ON public.daily_summaries(user_id, date DESC);

-- For analytics queries by date range across all users (admin/reporting)
CREATE INDEX idx_daily_summaries_date
  ON public.daily_summaries(date DESC);

-- ============================================================================
-- Row Level Security
-- ============================================================================

ALTER TABLE public.daily_summaries ENABLE ROW LEVEL SECURITY;

-- Users can only read their own summaries
CREATE POLICY "Users can read own summaries"
  ON public.daily_summaries
  FOR SELECT
  USING (auth.uid() = user_id);

-- No INSERT/UPDATE/DELETE policies for regular users
-- Summaries are created/updated by cron job running with SECURITY DEFINER (bypasses RLS)

-- ============================================================================
-- Comments
-- ============================================================================

COMMENT ON TABLE public.daily_summaries IS
  'Pre-aggregated daily statistics for fast analytics loading. Generated by hourly cron job.';

COMMENT ON COLUMN public.daily_summaries.date IS
  'Calendar date in user''s timezone (not UTC). One summary per user per date.';

COMMENT ON COLUMN public.daily_summaries.total_stints IS
  'Count of completed stints for this user on this date.';

COMMENT ON COLUMN public.daily_summaries.total_focus_seconds IS
  'Sum of actual_duration from all completed stints for this date.';

COMMENT ON COLUMN public.daily_summaries.total_pause_seconds IS
  'Sum of paused_duration from all completed stints for this date.';

COMMENT ON COLUMN public.daily_summaries.project_breakdown IS
  'JSONB array of per-project statistics: [{project_id, project_name, stint_count, focus_seconds}, ...]';

COMMENT ON COLUMN public.daily_summaries.completed_at IS
  'Timestamp when this summary was generated/last updated by the cron job.';
